import AsyncStorage from "@react-native-async-storage/async-storage";
import { NavigationContainer } from "@react-navigation/native";
import { createBottomTabNavigator } from "@react-navigation/bottom-tabs";
import { createNativeStackNavigator } from "@react-navigation/native-stack";
import { StatusBar } from "expo-status-bar";
import React, { useEffect, useState } from "react";
import { ActivityIndicator, Pressable, Text, View } from "react-native";
import { SafeAreaProvider, SafeAreaView } from "react-native-safe-area-context";
import { hasToken } from "./src/api";
import { LoginScreen, OTPScreen, RegisterScreen } from "./src/screens/AuthScreens";
import { AddVehicleScreen, BookingScreen, BookingSuccessScreen, BuildingScreen, HistoryScreen, HomeScreen, IncidentScreen, NotificationsScreen, PassesScreen, ProfileScreen, TicketScreen } from "./src/screens/MainScreens";
import { colors } from "./src/theme";
import { Button, s } from "./src/ui";

const Stack=createNativeStackNavigator();const Tabs=createBottomTabNavigator();
const slides=[{icon:"🔎",title:"Tìm chỗ đỗ dễ dàng",text:"Xem bãi xe và số chỗ trống theo thời gian thực."},{icon:"📍",title:"Đặt chỗ trước",text:"Chọn tầng, vị trí và thời gian bạn dự kiến đến."},{icon:"💳",title:"Thanh toán không tiền mặt",text:"Thanh toán nhanh và sử dụng vé QR tại cổng."}];

function Onboarding({done}:{done:()=>void}){const[i,setI]=useState(0);const finish=async()=>{await AsyncStorage.setItem("onboarded","true");done()};return <SafeAreaView style={[s.screen,{justifyContent:"space-between",padding:28}]}><View style={{alignItems:"flex-end"}}><Pressable onPress={finish}><Text style={{color:colors.muted,fontWeight:"700"}}>Bỏ qua</Text></Pressable></View><View style={{alignItems:"center",gap:20}}><Text style={{fontSize:110}}>{slides[i].icon}</Text><Text style={[s.title,{textAlign:"center"}]}>{slides[i].title}</Text><Text style={[s.subtitle,{textAlign:"center",fontSize:17}]}>{slides[i].text}</Text><View style={{flexDirection:"row",gap:8}}>{slides.map((_,x)=><View key={x} style={{height:8,width:x===i?28:8,borderRadius:8,backgroundColor:x===i?colors.primary:colors.border}}/>)}</View></View><Button title={i===slides.length-1?"BẮT ĐẦU NGAY":"TIẾP TỤC"} onPress={()=>i===slides.length-1?finish():setI(i+1)}/></SafeAreaView>}
function TabNavigator({onLogout}:{onLogout:()=>void}){return <Tabs.Navigator screenOptions={{headerShown:false,tabBarActiveTintColor:colors.primary,tabBarStyle:{height:64,paddingBottom:8,paddingTop:6}}}><Tabs.Screen name="Home" options={{title:"Trang chủ",tabBarIcon:()=> <Text>🏠</Text>}} component={HomeScreen}/><Tabs.Screen name="Ticket" options={{title:"Vé xe",tabBarIcon:()=> <Text>🎫</Text>}} component={TicketScreen}/><Tabs.Screen name="History" options={{title:"Lịch sử",tabBarIcon:()=> <Text>🧾</Text>}} component={HistoryScreen}/><Tabs.Screen name="Profile" options={{title:"Tài khoản",tabBarIcon:()=> <Text>👤</Text>}}>{p=><ProfileScreen {...p} onLogout={onLogout}/>}</Tabs.Screen></Tabs.Navigator>}
function Auth({onAuthenticated}:{onAuthenticated:()=>void}){return <Stack.Navigator><Stack.Screen name="Login" options={{headerShown:false}}>{p=><LoginScreen {...p} onAuthenticated={onAuthenticated}/>}</Stack.Screen><Stack.Screen name="Register" component={RegisterScreen} options={{title:"Đăng ký"}}/><Stack.Screen name="OTP" options={{title:"Xác thực"}}>{p=><OTPScreen {...p} onAuthenticated={onAuthenticated}/>}</Stack.Screen></Stack.Navigator>}
function Main({onLogout}:{onLogout:()=>void}){return <Stack.Navigator><Stack.Screen name="MainTabs" options={{headerShown:false}}>{()=> <TabNavigator onLogout={onLogout}/>}</Stack.Screen><Stack.Screen name="Building" component={BuildingScreen} options={{title:"Chi tiết bãi xe"}}/><Stack.Screen name="Booking" component={BookingScreen} options={{title:"Đặt chỗ"}}/><Stack.Screen name="BookingSuccess" component={BookingSuccessScreen} options={{headerShown:false}}/><Stack.Screen name="AddVehicle" component={AddVehicleScreen} options={{title:"Thêm phương tiện"}}/><Stack.Screen name="Incident" component={IncidentScreen} options={{title:"Hỗ trợ"}}/><Stack.Screen name="Passes" component={PassesScreen} options={{title:"Vé tháng"}}/><Stack.Screen name="Notifications" component={NotificationsScreen} options={{title:"Thông báo"}}/></Stack.Navigator>}
export default function App(){const[ready,setReady]=useState(false);const[onboarded,setOnboarded]=useState(false);const[authenticated,setAuthenticated]=useState(false);useEffect(()=>{setTimeout(async()=>{setOnboarded(Boolean(await AsyncStorage.getItem("onboarded")));setAuthenticated(await hasToken());setReady(true)},1600)},[]);let content;if(!ready)content=<View style={{flex:1,alignItems:"center",justifyContent:"center",backgroundColor:colors.primary}}><Text style={{fontSize:80}}>🅿️</Text><Text style={{color:"white",fontSize:25,fontWeight:"900"}}>PARKING DRIVER</Text><ActivityIndicator color="white" style={{marginTop:24}}/></View>;else if(!onboarded)content=<Onboarding done={()=>setOnboarded(true)}/>;else content=<NavigationContainer><StatusBar style="dark"/>{authenticated?<Main onLogout={()=>setAuthenticated(false)}/>:<Auth onAuthenticated={()=>setAuthenticated(true)}/>}</NavigationContainer>;return <SafeAreaProvider>{content}</SafeAreaProvider>}
