import AsyncStorage from "@react-native-async-storage/async-storage";
import * as LocalAuthentication from "expo-local-authentication";
import * as SecureStore from "expo-secure-store";
import React, { useState } from "react";
import { Alert, KeyboardAvoidingView, Platform, Pressable, ScrollView, Text, View } from "react-native";
import { api, storeToken } from "../api";
import { Button, Field, Screen, s } from "../ui";

export function LoginScreen({ navigation, onAuthenticated }: any) {
  const [phone, setPhone] = useState(""); const [password, setPassword] = useState(""); const [loading, setLoading] = useState(false);
  const login = async () => { try { setLoading(true); const x = await api<{access_token:string}>("/mobile/auth/login", { method: "POST", body: JSON.stringify({ phone, password }) }); await storeToken(x.access_token); await SecureStore.setItemAsync("biometric_credentials",JSON.stringify({phone,password})); await AsyncStorage.setItem("saved_phone", phone); onAuthenticated(); } catch (e:any) { Alert.alert("Đăng nhập thất bại", e.message); } finally { setLoading(false); } };
  const biometric = async () => { const saved = await SecureStore.getItemAsync("biometric_credentials"); if (!saved) return Alert.alert("Chưa thiết lập", "Hãy đăng nhập bằng mật khẩu lần đầu trên thiết bị này."); const compatible=await LocalAuthentication.hasHardwareAsync();const enrolled=await LocalAuthentication.isEnrolledAsync();if(!compatible||!enrolled)return Alert.alert("Không khả dụng","Thiết bị chưa cài Face ID hoặc vân tay.");const result = await LocalAuthentication.authenticateAsync({ promptMessage: "Đăng nhập Parking Driver",cancelLabel:"Hủy" }); if(result.success){try{setLoading(true);const credentials=JSON.parse(saved);const x=await api<{access_token:string}>("/mobile/auth/login",{method:"POST",body:JSON.stringify(credentials)});await storeToken(x.access_token);onAuthenticated()}catch(e:any){Alert.alert("Không thể đăng nhập",e.message)}finally{setLoading(false)}} };
  return <Screen><KeyboardAvoidingView behavior={Platform.OS === "ios" ? "padding" : undefined} style={{flex:1}}><ScrollView contentContainerStyle={[s.content,{paddingTop:70}]}><Text style={{fontSize:54,textAlign:"center"}}>🅿️</Text><Text style={[s.title,{textAlign:"center"}]}>Đăng nhập</Text><Text style={[s.subtitle,{textAlign:"center",marginBottom:18}]}>Tìm chỗ, đặt trước và thanh toán tiện lợi</Text><Field label="Số điện thoại" value={phone} onChangeText={setPhone} keyboardType="phone-pad" placeholder="09xxxxxxxx"/><Field label="Mật khẩu" value={password} onChangeText={setPassword} secureTextEntry placeholder="Tối thiểu 6 ký tự"/><Button title="ĐĂNG NHẬP" onPress={login} loading={loading} disabled={!phone || !password}/><Button title="Đăng nhập bằng Face ID / Vân tay" onPress={biometric} secondary/><Pressable onPress={()=>navigation.navigate("Register")}><Text style={{textAlign:"center",color:"#5B43EA",fontWeight:"700",padding:12}}>Chưa có tài khoản? Đăng ký</Text></Pressable></ScrollView></KeyboardAvoidingView></Screen>;
}

export function RegisterScreen({ navigation }: any) {
  const [form,setForm]=useState({full_name:"",phone:"",password:"",plate_number:"",vehicle_type_id:"1"}); const [loading,setLoading]=useState(false);
  const register=async()=>{try{setLoading(true);const x=await api<{demo_otp:string}>("/mobile/auth/register",{method:"POST",body:JSON.stringify({...form,vehicle_type_id:form.plate_number?Number(form.vehicle_type_id):null})});Alert.alert("OTP demo",`Mã xác thực: ${x.demo_otp}`);navigation.navigate("OTP",{phone:form.phone});}catch(e:any){Alert.alert("Không thể đăng ký",e.message)}finally{setLoading(false)}};
  return <Screen><ScrollView contentContainerStyle={s.content}><Text style={s.title}>Tạo tài khoản</Text><Text style={s.subtitle}>Đăng ký bằng số điện thoại của bạn.</Text><Field label="Họ và tên" value={form.full_name} onChangeText={v=>setForm({...form,full_name:v})}/><Field label="Số điện thoại" keyboardType="phone-pad" value={form.phone} onChangeText={v=>setForm({...form,phone:v})}/><Field label="Biển số xe mặc định (không bắt buộc)" autoCapitalize="characters" value={form.plate_number} onChangeText={v=>setForm({...form,plate_number:v})}/><Field label="Mã loại xe (1: xe máy, 2: ô tô)" keyboardType="number-pad" value={form.vehicle_type_id} onChangeText={v=>setForm({...form,vehicle_type_id:v})}/><Field label="Mật khẩu" secureTextEntry value={form.password} onChangeText={v=>setForm({...form,password:v})}/><Button title="ĐĂNG KÝ" onPress={register} loading={loading} disabled={!form.full_name||!form.phone||form.password.length<6}/></ScrollView></Screen>;
}

export function OTPScreen({ route, onAuthenticated }: any) {
  const phone=route.params.phone; const [code,setCode]=useState(""); const [loading,setLoading]=useState(false);
  const verify=async()=>{try{setLoading(true);const x=await api<{access_token:string}>("/mobile/auth/verify-otp",{method:"POST",body:JSON.stringify({phone,code})});await storeToken(x.access_token);onAuthenticated()}catch(e:any){Alert.alert("OTP không hợp lệ",e.message)}finally{setLoading(false)}};
  return <Screen><View style={[s.content,{paddingTop:80}]}><Text style={s.title}>Xác thực OTP</Text><Text style={s.subtitle}>Mã xác thực đã được gửi đến số {phone}. Trong bản demo, mã mặc định là 123456.</Text><Field value={code} onChangeText={setCode} keyboardType="number-pad" maxLength={6} placeholder="••••••" style={{textAlign:"center",fontSize:24,letterSpacing:10}}/><Button title="XÁC NHẬN" onPress={verify} loading={loading} disabled={code.length<4}/></View></Screen>;
}
