import * as ImagePicker from "expo-image-picker";
import React, { useCallback, useEffect, useState } from "react";
import { Alert, FlatList, Pressable, RefreshControl, ScrollView, Text, View } from "react-native";
import QRCode from "react-native-qrcode-svg";
import { api, clearToken } from "../api";
import { colors } from "../theme";
import { Booking, Building, BuildingDetail, Profile, Vehicle } from "../types";
import { Button, Card, Empty, Field, Screen, s } from "../ui";

const money=(n:number)=>new Intl.NumberFormat("vi-VN").format(n||0)+" ₫";
const date=(v:string)=>new Date(v).toLocaleString("vi-VN");
const localDateTime=(value:Date)=>{const offset=value.getTimezoneOffset()*60000;return new Date(value.getTime()-offset).toISOString().slice(0,16)};

export function HomeScreen({navigation}:any){const[data,setData]=useState<{greeting:string;unread_notifications:number;buildings:Building[]}|null>(null);const[search,setSearch]=useState("");const[refreshing,setRefreshing]=useState(false);const load=useCallback(async()=>{try{setData(await api(`/mobile/home?search=${encodeURIComponent(search)}`))}catch(e:any){Alert.alert("Lỗi",e.message)}finally{setRefreshing(false)}},[search]);useEffect(()=>{load()},[load]);return <Screen><FlatList contentContainerStyle={s.content} data={data?.buildings||[]} keyExtractor={x=>String(x.building_id)} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>{setRefreshing(true);load()}}/>} ListHeaderComponent={<View style={{gap:14}}><View style={s.row}><View><Text style={s.subtitle}>Chào buổi tốt lành</Text><Text style={s.title}>{data?.greeting?.replace("Xin chào, ","")||"Tài xế"}</Text></View><Pressable onPress={()=>navigation.navigate("Notifications")}><Text style={{fontSize:26}}>🔔{data?.unread_notifications?` ${data.unread_notifications}`:""}</Text></Pressable></View><Field value={search} onChangeText={setSearch} placeholder="Tìm kiếm bãi xe / tòa nhà..."/>{Boolean(data?.buildings.length)&&<Button title="📍 ĐẶT CHỖ NGAY" onPress={()=>navigation.navigate("Building",{id:data!.buildings[0].building_id})}/>}<View style={s.row}><Pressable style={{alignItems:"center"}} onPress={()=>navigation.navigate("Ticket")}><Text style={{fontSize:28}}>🎫</Text><Text style={s.value}>Vé xe</Text></Pressable><Pressable style={{alignItems:"center"}} onPress={()=>navigation.navigate("History")}><Text style={{fontSize:28}}>🧾</Text><Text style={s.value}>Lịch sử</Text></Pressable><Pressable style={{alignItems:"center"}} onPress={()=>navigation.navigate("Passes")}><Text style={{fontSize:28}}>📅</Text><Text style={s.value}>Vé tháng</Text></Pressable><Pressable style={{alignItems:"center"}} onPress={()=>navigation.navigate("Incident")}><Text style={{fontSize:28}}>🛟</Text><Text style={s.value}>Hỗ trợ</Text></Pressable></View><Text style={[s.value,{fontSize:19,marginTop:8}]}>Bãi xe đề xuất</Text></View>} ListEmptyComponent={<Empty text="Không tìm thấy bãi xe"/>} renderItem={({item})=><Pressable onPress={()=>navigation.navigate("Building",{id:item.building_id})}><Card><View style={s.row}><Text style={[s.value,{fontSize:17,flex:1}]}>{item.name}</Text><View style={s.badge}><Text style={s.badgeText}>{item.is_open?"Mở cửa":"Đóng cửa"}</Text></View></View><Text style={s.muted}>📍 {item.address}</Text><Text style={{color:colors.success,fontWeight:"800"}}>{item.available_slots}/{item.total_slots} chỗ trống</Text></Card></Pressable>}/></Screen>}

export function BuildingScreen({route,navigation}:any){const[id]=useState(route.params.id);const[data,setData]=useState<BuildingDetail|null>(null);const[vehicles,setVehicles]=useState<Vehicle[]>([]);useEffect(()=>{Promise.all([api<BuildingDetail>(`/mobile/buildings/${id}`),api<Vehicle[]>("/mobile/vehicles")]).then(([a,b])=>{setData(a);setVehicles(b)}).catch((e)=>Alert.alert("Lỗi",e.message))},[id]);if(!data)return <Screen><Empty text="Đang tải thông tin..."/></Screen>;return <Screen><ScrollView contentContainerStyle={s.content}><Text style={s.title}>{data.name}</Text><Text style={s.subtitle}>📍 {data.address}</Text><Card><Text style={[s.value,{fontSize:18}]}>Bảng giá</Text>{data.vehicle_types.map(x=><View key={x.vehicle_type_id} style={s.row}><Text>{x.name}</Text><Text style={s.value}>{money(x.hourly_price)}/giờ</Text></View>)}</Card><Text style={[s.value,{fontSize:18}]}>Khu vực còn chỗ</Text>{data.floors.map(f=><Card key={f.floor_id}><View style={s.row}><View><Text style={s.value}>{f.name}</Text><Text style={s.muted}>{f.available_slots}/{f.total_slots} chỗ trống</Text></View><Button title="ĐẶT CHỖ" disabled={!f.available_slots||!vehicles.length} onPress={()=>navigation.navigate("Booking",{building:data,floor:f,vehicles})}/></View></Card>)}{!vehicles.length&&<Text style={{color:colors.warning}}>Bạn cần thêm phương tiện trong Hồ sơ trước khi đặt chỗ.</Text>}</ScrollView></Screen>}

export function BookingScreen({route,navigation}:any){const{building,floor,vehicles}=route.params;const[vehicle,setVehicle]=useState<Vehicle>(vehicles.find((x:Vehicle)=>x.is_default)||vehicles[0]);const[slots,setSlots]=useState<any[]>([]);const[slot,setSlot]=useState<any>();const[arrival,setArrival]=useState(localDateTime(new Date(Date.now()+3600000)));const[payment,setPayment]=useState("MoMo");const[loading,setLoading]=useState(false);useEffect(()=>{api<any[]>(`/mobile/floors/${floor.floor_id}/available-slots?vehicle_type_id=${vehicle.vehicle_type_id}`).then(x=>{setSlots(x);setSlot(x[0])}).catch(e=>Alert.alert("Lỗi",e.message))},[floor.floor_id,vehicle]);const submit=async()=>{try{setLoading(true);const item=await api<Booking>("/mobile/bookings",{method:"POST",body:JSON.stringify({vehicle_id:vehicle.vehicle_id,building_id:building.building_id,floor_id:floor.floor_id,slot_id:slot.slot_id,arrival_time:arrival,payment_method:payment})});navigation.replace("BookingSuccess",{booking:item})}catch(e:any){Alert.alert("Đặt chỗ thất bại",e.message)}finally{setLoading(false)}};return <Screen><ScrollView contentContainerStyle={s.content}><Text style={s.title}>Đặt chỗ trước</Text><Card><Text style={s.value}>{building.name}</Text><Text style={s.muted}>{floor.name}</Text></Card><Text style={s.label}>Phương tiện</Text><View style={{flexDirection:"row",flexWrap:"wrap",gap:8}}>{vehicles.map((x:Vehicle)=><Pressable key={x.vehicle_id} onPress={()=>setVehicle(x)} style={[s.badge,{backgroundColor:x.vehicle_id===vehicle.vehicle_id?colors.primary:"white",borderWidth:1,borderColor:colors.border}]}><Text style={{color:x.vehicle_id===vehicle.vehicle_id?"white":colors.text,fontWeight:"700"}}>{x.plate_number}</Text></Pressable>)}</View><Field label="Thời gian dự kiến đến (YYYY-MM-DDTHH:mm)" value={arrival} onChangeText={setArrival}/><Text style={s.label}>Chọn vị trí</Text><View style={{flexDirection:"row",flexWrap:"wrap",gap:8}}>{slots.map(x=><Pressable key={x.slot_id} onPress={()=>setSlot(x)} style={{padding:12,borderRadius:10,backgroundColor:slot?.slot_id===x.slot_id?colors.primary:"white"}}><Text style={{color:slot?.slot_id===x.slot_id?"white":colors.text,fontWeight:"700"}}>{x.slot_code}</Text></Pressable>)}</View><Text style={s.label}>Thanh toán mô phỏng</Text><View style={{flexDirection:"row",flexWrap:"wrap",gap:8}}>{["MoMo","VNPay","ZaloPay","Thẻ ngân hàng"].map(x=><Pressable key={x} onPress={()=>setPayment(x)} style={[s.badge,{backgroundColor:payment===x?"#EDE9FE":"white"}]}><Text style={s.value}>{x}</Text></Pressable>)}</View><Button title="THANH TOÁN & ĐẶT CHỖ" onPress={submit} loading={loading} disabled={!slot}/></ScrollView></Screen>}

export function BookingSuccessScreen({route,navigation}:any){const b:Booking=route.params.booking;return <Screen><ScrollView contentContainerStyle={[s.content,{alignItems:"center",paddingTop:35}]}><Text style={{fontSize:60}}>✅</Text><Text style={[s.title,{textAlign:"center"}]}>Đặt chỗ thành công</Text><QRCode value={b.qr_token} size={210} color={colors.text}/><Text style={{fontSize:20,fontWeight:"900",letterSpacing:2}}>{b.booking_code}</Text><Card><Text style={s.value}>{b.building_name}</Text><Text style={s.muted}>{b.floor_name} • {b.slot_code}</Text><Text style={s.muted}>Biển số: {b.plate_number}</Text><Text style={s.muted}>Dự kiến: {date(b.arrival_time)}</Text><Text style={s.value}>Đã trả: {money(b.booking_fee)}</Text></Card><View style={{width:"100%",gap:10}}><Button title="XEM VÉ XE" onPress={()=>navigation.navigate("MainTabs",{screen:"Ticket"})}/><Button title="VỀ TRANG CHỦ" secondary onPress={()=>navigation.popToTop()}/></View></ScrollView></Screen>}

export function TicketScreen(){const[session,setSession]=useState<any>(undefined);const[booking,setBooking]=useState<Booking|undefined>();const load=useCallback(()=>Promise.all([api<any>("/mobile/active-session"),api<Booking[]>("/mobile/bookings")]).then(([a,b])=>{setSession(a);setBooking(b.find(x=>x.booking_status==="Confirmed"))}).catch(e=>Alert.alert("Lỗi",e.message)),[]);useEffect(()=>{load();const timer=setInterval(load,30000);return()=>clearInterval(timer)},[load]);const pay=async()=>{try{const x=await api<any>(`/mobile/active-session/${session.session_id}/pay`,{method:"POST",body:JSON.stringify({payment_method:"MoMo Demo"})});Alert.alert("Thanh toán thành công",`${money(x.amount)} • Có ${x.grace_period_minutes} phút để ra bãi.`);load()}catch(e:any){Alert.alert("Lỗi",e.message)}};if(session===undefined)return <Screen><Empty text="Đang đồng bộ vé..."/></Screen>;const qr=session?.qr_token||booking?.qr_token;if(!qr)return <Screen><Empty text="Bạn chưa có lượt gửi hoặc đặt chỗ đang hoạt động"/></Screen>;return <Screen><ScrollView contentContainerStyle={[s.content,{alignItems:"center"}]}><Text style={s.title}>Vé điện tử</Text><View style={s.badge}><Text style={s.badgeText}>{session?session.session_status:booking?.booking_status}</Text></View><QRCode value={qr} size={220}/><Text style={{fontSize:24,fontWeight:"900"}}>{session?.plate_number||booking?.plate_number}</Text><Card>{session?<><Text style={s.value}>📍 {session.floor_name} • {session.slot_code}</Text><Text style={s.muted}>Giờ vào: {date(session.entry_time)}</Text><Text style={[s.value,{fontSize:20}]}>Tạm tính: {money(session.estimated_amount)}</Text></>:<><Text style={s.value}>{booking?.building_name}</Text><Text style={s.muted}>{booking?.floor_name} • {booking?.slot_code}</Text><Text style={s.muted}>Dự kiến đến: {date(booking!.arrival_time)}</Text></>}</Card>{session&&session.payment_status!=="Paid"&&<View style={{width:"100%"}}><Button title="THANH TOÁN NGAY" onPress={pay}/></View>}<Text style={[s.muted,{textAlign:"center"}]}>Mã QR dùng để xác thực tại cổng. Dữ liệu tự cập nhật mỗi 30 giây.</Text></ScrollView></Screen>}

export function HistoryScreen(){const[tab,setTab]=useState("completed");const[data,setData]=useState<any>({parking_sessions:[],bookings:[]});useEffect(()=>{api(`/mobile/history?history_status=${tab}`).then(setData).catch(e=>Alert.alert("Lỗi",e.message))},[tab]);const all=[...data.parking_sessions,...data.bookings];return <Screen><View style={[s.content,{flex:1}]}><Text style={s.title}>Lịch sử giao dịch</Text><View style={s.row}><Button title="Đã hoàn thành" secondary={tab!=="completed"} onPress={()=>setTab("completed")}/><Button title="Đã hủy" secondary={tab!=="cancelled"} onPress={()=>setTab("cancelled")}/></View><FlatList data={all} keyExtractor={(x,i)=>String(x.id||x.booking_id||i)} ListEmptyComponent={<Empty text="Chưa có giao dịch"/>} renderItem={({item})=><Card><Text style={s.value}>{item.building_name||item.plate_number}</Text><Text style={s.muted}>{date(item.started_at||item.arrival_time)}</Text><View style={s.row}><Text>{item.status||item.booking_status}</Text><Text style={s.value}>{money(item.amount||item.booking_fee)}</Text></View></Card>}/></View></Screen>}

export function ProfileScreen({onLogout,navigation}:any){const[profile,setProfile]=useState<Profile|null>(null);const[vehicles,setVehicles]=useState<Vehicle[]>([]);const load=()=>Promise.all([api<Profile>("/mobile/profile"),api<Vehicle[]>("/mobile/vehicles")]).then(([a,b])=>{setProfile(a);setVehicles(b)});useEffect(()=>{load().catch(e=>Alert.alert("Lỗi",e.message))},[]);const logout=async()=>{await clearToken();onLogout()};return <Screen><ScrollView contentContainerStyle={s.content}><Text style={s.title}>Tài khoản</Text><Card><Text style={{fontSize:44,textAlign:"center"}}>👤</Text><Text style={[s.value,{fontSize:20,textAlign:"center"}]}>{profile?.full_name}</Text><Text style={[s.muted,{textAlign:"center"}]}>{profile?.phone}</Text></Card><View style={s.row}><Text style={[s.value,{fontSize:18}]}>Phương tiện của tôi</Text><Pressable onPress={()=>navigation.navigate("AddVehicle")}><Text style={{color:colors.primary,fontWeight:"800"}}>+ Thêm xe</Text></Pressable></View>{vehicles.map(x=><Card key={x.vehicle_id}><View style={s.row}><View><Text style={s.value}>{x.plate_number}</Text><Text style={s.muted}>{x.vehicle_type_name}{x.color?` • ${x.color}`:""}</Text></View>{x.is_default&&<View style={s.badge}><Text style={s.badgeText}>Mặc định</Text></View>}</View></Card>)}<Button title="Quản lý vé tháng" secondary onPress={()=>navigation.navigate("Passes")}/><Button title="Phản hồi & Báo cáo sự cố" secondary onPress={()=>navigation.navigate("Incident")}/><Button title="ĐĂNG XUẤT" danger onPress={logout}/></ScrollView></Screen>}

export function AddVehicleScreen({navigation}:any){const[form,setForm]=useState({plate_number:"",vehicle_type_id:"1",color:"",is_default:true});const save=async()=>{try{await api("/mobile/vehicles",{method:"POST",body:JSON.stringify({...form,vehicle_type_id:Number(form.vehicle_type_id)})});Alert.alert("Thành công","Đã thêm phương tiện");navigation.goBack()}catch(e:any){Alert.alert("Lỗi",e.message)}};return <Screen><View style={s.content}><Text style={s.title}>Thêm phương tiện</Text><Field label="Biển số" autoCapitalize="characters" value={form.plate_number} onChangeText={v=>setForm({...form,plate_number:v})}/><Field label="Mã loại xe (1: xe máy, 2: ô tô)" value={form.vehicle_type_id} keyboardType="number-pad" onChangeText={v=>setForm({...form,vehicle_type_id:v})}/><Field label="Màu xe" value={form.color} onChangeText={v=>setForm({...form,color:v})}/><Button title="LƯU PHƯƠNG TIỆN" onPress={save} disabled={!form.plate_number}/></View></Screen>}

export function IncidentScreen(){const[type,setType]=useState("Lỗi thanh toán");const[description,setDescription]=useState("");const[image,setImage]=useState<string>();const[items,setItems]=useState<any[]>([]);const load=()=>api<any[]>("/mobile/incidents").then(setItems);useEffect(()=>{load()},[]);const pick=async()=>{const r=await ImagePicker.launchImageLibraryAsync({mediaTypes:["images"],quality:.7});if(!r.canceled)setImage(r.assets[0].uri)};const submit=async()=>{try{await api("/mobile/incidents",{method:"POST",body:JSON.stringify({incident_type:type,description,image_url:image})});setDescription("");setImage(undefined);Alert.alert("Đã gửi","Ban quản lý sẽ phản hồi sớm nhất.");load()}catch(e:any){Alert.alert("Lỗi",e.message)}};return <Screen><ScrollView contentContainerStyle={s.content}><Text style={s.title}>Báo cáo sự cố</Text><Text style={s.label}>Loại sự cố</Text><View style={{flexDirection:"row",flexWrap:"wrap",gap:8}}>{["Lỗi thanh toán","Sai vị trí đỗ","Thiết bị hỏng","Thái độ nhân viên","Khác"].map(x=><Pressable key={x} onPress={()=>setType(x)} style={[s.badge,{backgroundColor:type===x?"#EDE9FE":"white"}]}><Text style={s.value}>{x}</Text></Pressable>)}</View><Field label="Mô tả chi tiết (ít nhất 10 ký tự)" multiline value={description} onChangeText={setDescription} style={{height:110,textAlignVertical:"top",paddingTop:14}}/><Button title={image?"✓ Đã chọn ảnh":"Thêm hình ảnh minh họa"} secondary onPress={pick}/><Button title="GỬI BÁO CÁO" onPress={submit} disabled={description.length<10}/><Text style={[s.value,{fontSize:18}]}>Báo cáo đã gửi</Text>{items.map(x=><Card key={x.incident_id}><View style={s.row}><Text style={s.value}>#{x.incident_id} • {x.incident_type}</Text><Text style={{color:colors.info}}>{x.status}</Text></View><Text style={s.muted}>{x.description}</Text>{x.manager_response&&<Text>Phản hồi: {x.manager_response}</Text>}</Card>)}</ScrollView></Screen>}

export function PassesScreen(){
  const[items,setItems]=useState<any[]>([]);const[vehicles,setVehicles]=useState<Vehicle[]>([]);
  const[buildings,setBuildings]=useState<Building[]>([]);const[vehicleId,setVehicleId]=useState<number>();
  const[buildingId,setBuildingId]=useState<number>();const[months,setMonths]=useState(1);const[loading,setLoading]=useState(false);
  const load=()=>Promise.all([api<any[]>("/mobile/monthly-passes"),api<Vehicle[]>("/mobile/vehicles"),api<any>("/mobile/home")]).then(([p,v,h])=>{setItems(p);setVehicles(v);setBuildings(h.buildings);if(!vehicleId&&v[0])setVehicleId(v[0].vehicle_id);if(!buildingId&&h.buildings[0])setBuildingId(h.buildings[0].building_id)});
  useEffect(()=>{load().catch(e=>Alert.alert("Lỗi",e.message))},[]);
  const buy=async()=>{try{setLoading(true);await api("/mobile/monthly-passes",{method:"POST",body:JSON.stringify({vehicle_id:vehicleId,building_id:buildingId,months,payment_method:"MoMo Demo"})});Alert.alert("Thành công","Đã mua vé tháng");await load()}catch(e:any){Alert.alert("Không thể mua vé",e.message)}finally{setLoading(false)}};
  const renew=async(item:any)=>{try{setLoading(true);await api(`/mobile/monthly-passes/${item.monthly_pass_id}/renew`,{method:"POST",body:JSON.stringify({vehicle_id:item.vehicle_id,building_id:item.building_id,months:1,payment_method:"MoMo Demo"})});Alert.alert("Thành công","Đã gia hạn thêm 1 tháng");await load()}catch(e:any){Alert.alert("Không thể gia hạn",e.message)}finally{setLoading(false)}};
  return <Screen><ScrollView contentContainerStyle={s.content}><Text style={s.title}>Vé tháng</Text><Card><Text style={[s.value,{fontSize:18}]}>Mua vé tháng mới</Text><Text style={s.label}>Chọn phương tiện</Text><View style={{flexDirection:"row",flexWrap:"wrap",gap:8}}>{vehicles.map(v=><Pressable key={v.vehicle_id} onPress={()=>setVehicleId(v.vehicle_id)} style={[s.badge,{backgroundColor:vehicleId===v.vehicle_id?colors.primary:"white"}]}><Text style={{color:vehicleId===v.vehicle_id?"white":colors.text,fontWeight:"700"}}>{v.plate_number}</Text></Pressable>)}</View><Text style={s.label}>Chọn bãi xe</Text>{buildings.map(b=><Pressable key={b.building_id} onPress={()=>setBuildingId(b.building_id)} style={[s.badge,{backgroundColor:buildingId===b.building_id?"#EDE9FE":"white"}]}><Text style={s.value}>{b.name}</Text></Pressable>)}<Text style={s.label}>Thời hạn</Text><View style={s.row}>{[1,3,6].map(m=><Pressable key={m} onPress={()=>setMonths(m)} style={[s.badge,{backgroundColor:months===m?colors.primary:"white"}]}><Text style={{color:months===m?"white":colors.text,fontWeight:"700"}}>{m} tháng</Text></Pressable>)}</View><Button title="MUA VÉ THÁNG" onPress={buy} loading={loading} disabled={!vehicleId||!buildingId}/></Card><Text style={[s.value,{fontSize:18}]}>Vé tháng của tôi</Text>{items.length?items.map(x=><Card key={x.monthly_pass_id}><View style={s.row}><Text style={s.value}>{x.pass_code}</Text><View style={s.badge}><Text style={s.badgeText}>{x.status}</Text></View></View><Text>{x.building_name}</Text><Text style={s.muted}>{x.plate_number} • Hết hạn {date(x.end_date)}</Text><Text style={s.value}>{money(x.amount)}</Text><Button title="GIA HẠN 1 THÁNG" secondary onPress={()=>renew(x)} loading={loading}/></Card>):<Empty text="Bạn chưa có vé tháng"/>}</ScrollView></Screen>
}

export function NotificationsScreen(){const[items,setItems]=useState<any[]>([]);const load=()=>api<any[]>("/mobile/notifications").then(setItems);useEffect(()=>{load()},[]);const read=async(id:number)=>{await api(`/mobile/notifications/${id}/read`,{method:"PUT"});load()};return <Screen><FlatList contentContainerStyle={s.content} data={items} keyExtractor={x=>String(x.notification_id)} ListHeaderComponent={<Text style={s.title}>Thông báo</Text>} ListEmptyComponent={<Empty text="Chưa có thông báo"/>} renderItem={({item})=><Pressable onPress={()=>read(item.notification_id)}><Card><View style={s.row}><Text style={s.value}>{item.title}</Text>{!item.is_read&&<View style={{width:9,height:9,borderRadius:9,backgroundColor:colors.primary}}/>}</View><Text style={s.muted}>{item.message}</Text><Text style={{fontSize:12,color:colors.muted}}>{date(item.created_at)}</Text></Card></Pressable>}/></Screen>}
